##From LIB lmprot famz
# "SELAMAT DATANG"
# by BINTANG XD
#[1] Login via token
#[2] login cokies
#1FROM FRADLIS/TEMAN
#2FROM ID MASAL
#3FROM ID GRUP
#4FROM ID OLD
#5CEK HASIL CRACK
#6USER AGENT
#00HAPUS TOKEN/COKIES
