##From LIB lmprot famz
##blue=['\033[34;1m'LAM-TIM
##by BINTANG XD
##[1] Login via token
##[2] login cokies
##1FROM FRADLIS/TEMAN
##2FROM ID MASAL
##3FROM ID GRUP
##4FROM ID OLD
##5CEK HASIL CRACK
##6USER AGENT
##00HAPUS TOKEN/COKIES
